[Deep Learning Book](https://www.deeplearningbook.com.br/)

### Exemplo de aplicação de Redes Neurais:

- Baseado no trabalho de [Sagar Howal](https://towardsdatascience.com/neural-networks-with-google-colaboratory-artificial-intelligence-getting-started-713b5eb07f14)

- Usaremos dados a respeito de *câncer de mama*, diponíveis no [Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets.php), para construir uma **Rede Neural** para diagnosticar câncer de mama a partir de imagens. A base de dados contém informações descrevendo algumas características das células identificadas nas imagens. A última coluna traz o diagnóstico (2 indica **câncer benígno** e 4 indica **cancer malígno**  )
    - [Dados](https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data)
    - [Descrição dos dados](https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.names)

###Descrição dos dados:

- Número de instâncias: 569 

- Número de atritutos: 32 (ID, diagnóstico, 30 valores reais de entrada)

- Informação sobre os atributos:

1) ID numérico

2) Diagnóstico (M = malígno, B = benígno)

3-32) Dez valores reais de características computados para cada núcleo de célula:

	a) radius (média das distâncias do centro até um ponto no perímetro)
	b) texture (desvio padrão dos valores na escala de cinza)
	c) perimeter
	d) area
	e) smoothness (variação local no comprimento do raio)
	f) compactness (perimeter^2 / area - 1.0)
	g) concavity (severidade de porções côncavas do contorno)
	h) concave points (número de de porções côncavas do contorno)
	i) symmetry 
	j) fractal dimension ("coastline approximation" - 1)


In [1]:
names = ['ID',
         'Diag',
         'radius1',
         'texture1', 
         'perimeter1', 
         'area1',
         'smoothness1', 
         'compactness1',
         'concavity1', 
         'concave points1',
         'symmetry1',
         'fractal dimension1',
         'radius2',
         'texture2', 
         'perimeter2', 
         'area2',
         'smoothness2', 
         'compactness2',
         'concavity2',
         'concave points2',
         'symmetry2',
         'fractal dimension2',
         'radius3',
         'texture3', 
         'perimeter3', 
         'area3',
         'smoothness3', 
         'compactness3',
         'concavity3',
         'concave points3',
         'symmetry3',
         'fractal dimension3']


In [4]:
#Carregando o dataset - "breast_cancer.csv"
from google.colab import files
uploaded = files.upload()

Saving wdbc.data to wdbc.data


In [5]:
!ls

breast_cancer.csv  sample_data	wdbc.data


In [6]:
import pandas as pd
import requests
import matplotlib.pyplot as pt
import numpy as np
import io

#Alternativamente pode-se obter o dataset do repositório
link = "http://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"
csv_text = requests.get(link).text
dataset = pd.read_csv(io.StringIO(csv_text))
dataset.to_csv('breast_cancer.csv')

for nome, data in uploaded.items():
  with open("breast_cancer.csv", 'wb') as f:
    f.write(data)

#Mostra as 10 primeiras linhas do dataset. 
dataset.head(10)


842302  M  17.99  10.38   122.8  ...  0.6656  0.7119   0.2654  0.4601   0.1189
0    842517  M  20.57  17.77  132.90  ...  0.1866  0.2416  0.18600  0.2750  0.08902
1  84300903  M  19.69  21.25  130.00  ...  0.4245  0.4504  0.24300  0.3613  0.08758
2  84348301  M  11.42  20.38   77.58  ...  0.8663  0.6869  0.25750  0.6638  0.17300
3  84358402  M  20.29  14.34  135.10  ...  0.2050  0.4000  0.16250  0.2364  0.07678
4    843786  M  12.45  15.70   82.57  ...  0.5249  0.5355  0.17410  0.3985  0.12440
5    844359  M  18.25  19.98  119.60  ...  0.2576  0.3784  0.19320  0.3063  0.08368
6  84458202  M  13.71  20.83   90.20  ...  0.3682  0.2678  0.15560  0.3196  0.11510
7    844981  M  13.00  21.82   87.50  ...  0.5401  0.5390  0.20600  0.4378  0.10720
8  84501001  M  12.46  24.04   83.97  ...  1.0580  1.1050  0.22100  0.4366  0.20750
9    845636  M  16.02  23.24  102.70  ...  0.1551  0.1459  0.09975  0.2948  0.08452

[10 rows x 32 columns]

In [7]:
#Inserção de rótulos para as colunas
#Se não importam os nomes das colunas, substitua "names=names" por "headers=None"
l_dataset = pd.read_csv(io.StringIO(csv_text), names=names)
l_dataset.to_csv('breast_cancer_label.csv',sep=',', encoding='utf-8')
                 
#df.to_csv('breast_cancer_lab.csv',sep='\t', encoding='utf-8')

#Mostra as 10 primeiras linhas do dataset. 
l_dataset.head(10)


ID Diag  radius1  ...  concave points3  symmetry3  fractal dimension3
0    842302    M    17.99  ...           0.2654     0.4601             0.11890
1    842517    M    20.57  ...           0.1860     0.2750             0.08902
2  84300903    M    19.69  ...           0.2430     0.3613             0.08758
3  84348301    M    11.42  ...           0.2575     0.6638             0.17300
4  84358402    M    20.29  ...           0.1625     0.2364             0.07678
5    843786    M    12.45  ...           0.1741     0.3985             0.12440
6    844359    M    18.25  ...           0.1932     0.3063             0.08368
7  84458202    M    13.71  ...           0.1556     0.3196             0.11510
8    844981    M    13.00  ...           0.2060     0.4378             0.10720
9  84501001    M    12.46  ...           0.2210     0.4366             0.20750

[10 rows x 32 columns]

In [8]:
#from google.colab import data_table
#data_table.enable_dataframe_formatter()

#from google.colab import data_table
#data_table.disable_dataframe_formatter()

In [9]:
!ls

breast_cancer.csv  breast_cancer_label.csv  sample_data  wdbc.data


In [10]:
#Separa as variáveis dependentes da independentes. 

X = dataset.iloc[:, 2:32].values  #Nota: exclui a última coluna todos os valores NaN.
y = dataset.iloc[:, 1].values

- Os valores **M** (malígno) e **B** (benígno) devem ser convertidos para valores numérios, por ex. '1' e '0'.

In [11]:
#Codificando os dados categóricos
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

y = labelencoder.fit_transform(y)

In [12]:
X

array([[2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       [1.142e+01, 2.038e+01, 7.758e+01, ..., 2.575e-01, 6.638e-01,
        1.730e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [13]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,

In [14]:
#Separando o dataset em conjuntos de Treinamento (80%) e de Teste(20%)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)


- Usaremos a **API [Keras](https://keras.io/)** para trabalharmos com Redes Neurais Artificiais
- Esta API requer **[Tensorflow](https://www.tensorflow.org/)** ou **Theano** para a execução de operações subjacentes. O Colaboratory já tem o Tensoflow instalado na máquina virtual.
- Para instalar um versão específica do Tensorflow, use: *!pip install tensorflow==XXX (XXX = versão)*
- Para instalar o Keras: *!pip install  keras*

In [15]:
!pip show tensorflow #identica a versão do Tensorflow instalada

Name: tensorflow
Version: 2.8.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: flatbuffers, h5py, opt-einsum, keras-preprocessing, astunparse, six, grpcio, google-pasta, keras, libclang, gast, tf-estimator-nightly, absl-py, typing-extensions, setuptools, protobuf, numpy, tensorflow-io-gcs-filesystem, tensorboard, wrapt, termcolor
Required-by: kapre


In [16]:
# Importando as bibliotecas do pacote Keras
import keras
from keras.models import Sequential
from keras.layers import Dense

In [17]:
# Inicializando a ANN
classifier = Sequential()

###Especificação do parâmetros da rede neural

- **units**:  número de neurônios
- **kernel_initializer**: valores iniciais dos pesos
- **activation**: define a função de ativação

- **Primeira camada**: 5 neurônios, com pesos inicializados uniformemente e ativado pela função  ([ReLU](http://deeplearningbook.com.br/funcao-de-ativacao/)). Também definimos a dimensão do nosso *dataset* (9 colunas). Uma forma simples de determinar o número de neurônios em uma camada é dividir o número de colunas total do dataset por 2: (9+1)/2=5

- **Segunda camada**: idêntica à primeira, mas sem o parâmetro *input_dim*

- **Camada de saida**: a saída da rede tem apenas dois valores. Desta forma, basta um neurônio nesta camada. Ele terá peso uniformemente inicializado. Usaremos a função de ativação ([sigmoide](http://deeplearningbook.com.br/funcao-de-ativacao/))

In [18]:
# Adicionando a camada de entrada e a primeira camada oculta
classifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'relu', input_dim = 30))

# Adicionando a segunda camada oculta
classifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'relu'))

# Adicionando a camada de saída
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compilando a ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

- Executando:
   - **batch_size**: indica o número de entradas a serem processadas simultaneamente
   - **epoch**:  indica o  passagem  completa sobre todo o dataset.

In [19]:
# Adequando a ANN ao conjunto de treinamento
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
46/46 [==============================] - 1s 2ms/step - loss: 0.6504 - accuracy: 0.5110
Epoch 2/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5123 - accuracy: 0.8789
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.3454 - accuracy: 0.8965
Epoch 4/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2827 - accuracy: 0.9075
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2479 - accuracy: 0.8987
Epoch 6/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2366 - accuracy: 0.9163
Epoch 7/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2428 - accuracy: 0.8987
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2393 - accuracy: 0.9075
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2448 - accuracy: 0.9031
Epoch 10/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2797 - accuracy: 0.9009
Epoch 11/

In [20]:
# Fazendo as previsões sobre o conjunto de testes
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Construindo a Matriz de Confusão
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred) 

In [21]:
cm

array([[68,  0],
       [ 8, 38]])

**Resultados**:

- 64 negativos verdadeiros, 4 falsos positivos, 4 falsos negativos e 41 negativos verdadeiros -> **8 predições erradas**.